name: angel_firebase
version: 1.0.0
description: Firebase-enabled services for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/firebase
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  firebase: ^3.0.0
dev_dependencies:
  angel_configuration: ^1.0.0
  angel_diagnostics: ^1.0.0
  angel_test: ^1.0.0
  googleapis: ^0.40.0
  googleapis_auth: ^0.2.0
  test: ^0.12.0